export const GOOGLE_CLIENT_ID= process.env.GOOGLE_CLIENT_ID || '1054628170969-58dlvsrtcenqf8n1kd86mlk09cf16dum.apps.googleusercontent.com'
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || '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'
export const SERVER_ROOT_URI = 'http://localhost:4000'
export const UI_ROOT_URI = 'http://localhost:3000'
export const JWT_SECRET = 'bnjabhai'
export const COOKIE_NAME = 'auth_token'